import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    UpdateDateColumn,
    Index,
} from 'typeorm';

export enum RecipeDifficulty {
    EASY = 'easy',
    MEDIUM = 'medium',
    HARD = 'hard',
}

@Entity('recipes')
export class Recipe {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ length: 255 })
    title: string;

    @Column({ type: 'text', nullable: true })
    description: string;

    @Column('simple-array')
    ingredients: string[];

    @Column('simple-json')
    steps: string[];

    @Column({ type: 'int', default: 30 })
    estimatedTime: number; // in minutes

    @Column({
        type: 'enum',
        enum: RecipeDifficulty,
        default: RecipeDifficulty.MEDIUM,
    })
    difficulty: RecipeDifficulty;

    @Column('simple-array', { nullable: true })
    safetyNotes: string[];

    @Column('simple-array', { nullable: true })
    tags: string[];

    @Column({ type: 'float', nullable: true })
    rating: number;

    @Column({ type: 'int', default: 0 })
    ratingCount: number;

    @Index()
    @Column({ length: 64, nullable: true })
    inputFingerprint: string; // hash of ingredients for caching

    @Column({ type: 'boolean', default: false })
    isGenerated: boolean; // true if generated by LLM

    @Column({ type: 'boolean', default: false })
    isSaved: boolean; // true if bookmarked/saved by user

    @Index()
    @Column({ length: 64, nullable: true })
    sessionId: string; // anonymous session ID

    @Column({ type: 'simple-json', nullable: true })
    embedding: number[]; // vector embedding for similarity search

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
